import { writeFileSync } from 'fs';
import { join } from 'path';
import type { SkillModule } from '../types.js';
import { composeSections } from './utils.js';

/**
 * Codex / OpenAI — AGENTS.md at project root
 */
export function generateCodex(modules: SkillModule[], targetDir: string): void {
  const header = `# AGENTS.md\n\nGenerated by @saritasa/fe-skills. Do not edit manually.\n\n`;
  const content = header + composeSections(modules);
  writeFileSync(join(targetDir, 'AGENTS.md'), content, 'utf-8');
}
